spring.application.name=demo
spring.jackson.deserialization.fail-on-null-for-primitives=false

# API externa que se va a consumir para el catálogo de productos
app.dummyjson.base-url=https://dummyjson.com
